import itemsImg from "./itemsImg"

const data = [
    {
        id: 1,
        name: 'Car loan',
        description: 'Interest rate: 3.5%',
        cycle: 1,
        price: 99.99,
        thumbnail: itemsImg.car,
    },
    {
        id: 2,
        name: 'Car insurance',
        description: 'Agency: ',
        cycle: 1,
        price: 49.99,
        thumbnail: itemsImg.carInsurance,
    },
    {
        id: 3,
        name: 'Gas',
        description: 'Car gas',
        cycle: 1,
        price: 99.99,
        thumbnail: itemsImg.gas,
    },
    {
        id: 4,
        name: 'Grocery',
        description: 'All groceries',
        cycle: 1,
        price: 899.99,
        thumbnail: itemsImg.grocery,
    },
    {
        id: 5,
        name: 'Gym',
        description: 'Gym membership',
        cycle: 1,
        price: 49.99,
        thumbnail: itemsImg.gym,
    },
    {
        id: 6,
        name: 'Health Insurance',
        description: 'Insurance company: ',
        cycle: 1,
        price: 199.99,
        thumbnail: itemsImg.healthInsurance,
    },
    {
        id: 7,
        name: 'Home Insurance',
        description: 'Insurance company: ',
        cycle: 1,
        price: 49.99,
        thumbnail: itemsImg.homeInsurance,
    },
    {
        id: 8,
        name: 'Loan',
        description: 'Interest rate: 3.5%',
        cycle: 1,
        price: 699.99,
        thumbnail: itemsImg.loan,
    },
    {
        id: 9,
        name: 'Payment',
        description: 'Regular payment',
        cycle: 1,
        price: 49.99,
        thumbnail: itemsImg.pay,
    },
    {
        id: 10,
        name: 'Cellphone',
        description: 'Phone bill',
        cycle: 1,
        price: 49.99,
        thumbnail: itemsImg.phone,
    },
    {
        id: 11,
        name: 'Rent',
        description: 'Apartment rent',
        cycle: 1,
        price: 49.99,
        thumbnail: itemsImg.rent,
    },
    {
        id: 12,
        name: 'Internet',
        description: 'Internet bill',
        cycle: 1,
        price: 69.99,
        thumbnail: itemsImg.wifi,
    },
    // Companies
    {
        id: 13,
        name: 'Playstation',
        description: 'Playstation Plus',
        cycle: 3,
        price: 59.99,
        thumbnail: itemsImg.playstation,
    },
    {
        id: 14,
        name: 'Xbox',
        description: 'Game Pass Ultimate',
        cycle: 1,
        price: 14.99,
        thumbnail: itemsImg.xbox,
    },
    {
        id: 15,
        name: 'Spotify',
        description: 'Spotify Premium',
        cycle: 1,
        price: 14.99,
        thumbnail: itemsImg.spotify,
    },
    {
        id: 16,
        name: 'Amazon',
        description: 'Prime',
        cycle: 1,
        price: 17.99,
        thumbnail: itemsImg.amazon,
    },
    {
        id: 17,
        name: 'Netflix',
        description: 'Netflix Premium',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.netflix,
    },
    {
        id: 18,
        name: 'Twitch',
        description: 'Channel subscription',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.twitch,
    },
    {
        id: 19,
        name: 'Youtube',
        description: 'Youtube Premium',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.youtube,
    },
    {
        id: 20,
        name: 'Patreon',
        description: 'Channel subscription',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.patreon,
    },
    {
        id: 21,
        name: 'Shopify',
        description: 'Shopify account',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.shopify,
    },
    {
        id: 22,
        name: 'Google Play',
        description: 'Google Play services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.googlePlay,
    },
    {
        id: 23,
        name: 'App Store',
        description: 'App Store services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.appStore,
    },
    {
        id: 24,
        name: 'Hulu',
        description: 'Hulu services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.hulu,
    },
    {
        id: 25,
        name: 'Roku',
        description: 'Roku services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.roku,
    },
    {
        id: 26,
        name: 'Google',
        description: 'Google services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.google,
    },
    {
        id: 27,
        name: 'Expenses',
        description: 'Other expenses',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.expenses,
    },
    {
        id: 28,
        name: 'Fashion',
        description: 'Fashion expenses',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.fashion,
    },
    {
        id: 29,
        name: 'Beauty',
        description: 'Beauty products',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.beauty,
    },
    {
        id: 30,
        name: 'Pet Care',
        description: 'Pets expenses',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.pet,
    },
    {
        id: 31,
        name: 'HBO',
        description: 'HBO premium',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.hbo,
    },
    {
        id: 32,
        name: 'Apple',
        description: 'Apple services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.apple,
    },
    {
        id: 33,
        name: 'Audible',
        description: 'Audible premium',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.audible,
    },
    {
        id: 34,
        name: 'Gaming',
        description: 'Gaming expenses',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.gaming,
    },
    {
        id: 35,
        name: 'Roblox',
        description: 'Roblox games',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.roblox,
    },
    {
        id: 36,
        name: 'Github',
        description: 'Github services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.github,
    },
    {
        id: 37,
        name: 'Adobe',
        description: 'Adobe services',
        cycle: 1,
        price: 49.99,
        thumbnail: itemsImg.adobe,
    },
    {
        id: 38,
        name: 'Microsoft',
        description: 'Microsoft services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.microsoft,
    },
    {
        id: 39,
        name: 'Slack',
        description: 'Slack subscription',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.slack,
    },
    {
        id: 40,
        name: 'Crunchyroll',
        description: 'Crunchyroll premium',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.crunchyroll,
    },
    {
        id: 41,
        name: 'Zoom',
        description: 'Zoom services',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.zoom,
    },
    {
        id: 42,
        name: 'Alcohol',
        description: 'Alcohol expenses',
        cycle: 1,
        price: 99.99,
        thumbnail: itemsImg.alcohol,
    },
    {
        id: 43,
        name: 'Bars',
        description: 'Bars expenses',
        cycle: 1,
        price: 99.99,
        thumbnail: itemsImg.bar,
    },
    {
        id: 44,
        name: 'Coffee / Tea',
        description: 'Coffee / Tea expenses',
        cycle: 1,
        price: 99.99,
        thumbnail: itemsImg.coffee,
    },
    {
        id: 45,
        name: 'House Keeping',
        description: 'House Keeping expenses',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.housekeeping,
    },
    {
        id: 46,
        name: 'Dining Out',
        description: 'Dining Out expenses',
        cycle: 1,
        price: 299.99,
        thumbnail: itemsImg.foodService,
    },
    {
        id: 47,
        name: 'Transportation',
        description: 'Medicine expenses',
        cycle: 1,
        price: 99.99,
        thumbnail: itemsImg.transportation,
    },
    {
        id: 48,
        name: 'Education',
        description: 'Education expenses',
        cycle: 12,
        price: 4000.00,
        thumbnail: itemsImg.education,
    },
    {
        id: 49,
        name: 'Water',
        description: 'Water expenses',
        cycle: 1,
        price: 9.99,
        thumbnail: itemsImg.water,
    },
    {
        id: 50,
        name: 'Child Care',
        description: 'Child care expenses',
        cycle: 1,
        price: 599.99,
        thumbnail: itemsImg.children,
    },
    {
        id: 51,
        name: 'Tobacco',
        description: 'Tobacco expenses',
        cycle: 1,
        price: 599.99,
        thumbnail: itemsImg.tobacco,
    },
    {
        id: 52,
        name: 'Utilities',
        description: 'Utilities expenses',
        cycle: 1,
        price: 399.99,
        thumbnail: itemsImg.utilities,
    },
]

export default data